name: Unit Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v2
      - run: npm ci

      - name: end-to-end-tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e:ci
